Add libasound2-dev as required package
The recently added ALSA support requires the libasound2-dev package to
be able to compile on a Jessy based Raspbian.

This fixes the following compile error:

~~~~~
linux/OMXAlsa.cpp:21:28: fatal error: alsa/asoundlib.h: No such file or directory compilation terminated.
Makefile:46: recipe for target 'linux/OMXAlsa.o' failed
make: *** [linux/OMXAlsa.o] Error 1
~~~~~

Fixes: c84083d15cbd ("Initial alsa support")